-- Wild Australia: Evolution Clash — Online Multiplayer foundation
-- Run this in the connected Supabase project SQL editor.
-- Anonymous sign-ins must be enabled in Supabase Auth.

create extension if not exists pgcrypto;

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  code text not null unique check (char_length(code)=6),
  host_user_id uuid not null,
  status text not null default 'lobby' check (status in ('lobby','ready','playing','finished')),
  round int not null default 1 check (round between 1 and 4),
  phase text not null default 'free',
  predation_stage int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.room_players (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.rooms(id) on delete cascade,
  user_id uuid not null,
  name text not null check (char_length(name) between 1 and 24),
  seat int not null check (seat between 1 and 10),
  life int not null default 20,
  alive boolean not null default true,
  skills jsonb not null default '[]'::jsonb,
  card_count int not null default 10,
  joined_at timestamptz not null default now(),
  unique(room_id,user_id),
  unique(room_id,seat)
);

create table if not exists public.player_secrets (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.rooms(id) on delete cascade,
  user_id uuid not null,
  role_id text,
  predation_cards int[] not null default array[1,2,3,4,5,6,7,8,9,10],
  created_at timestamptz not null default now(),
  unique(room_id,user_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  user_id uuid not null,
  sender_name text not null,
  body text not null check (char_length(body) between 1 and 220),
  created_at timestamptz not null default now()
);

alter table public.rooms enable row level security;
alter table public.room_players enable row level security;
alter table public.player_secrets enable row level security;
alter table public.messages enable row level security;

-- Lobby discovery is intentionally limited to authenticated/anonymous Supabase users.
create policy "rooms_read_authenticated" on public.rooms for select to authenticated using (true);
create policy "rooms_create_self_host" on public.rooms for insert to authenticated with check (host_user_id=auth.uid());
create policy "rooms_host_update" on public.rooms for update to authenticated using (host_user_id=auth.uid()) with check (host_user_id=auth.uid());

create policy "players_read_authenticated" on public.room_players for select to authenticated using (true);
create policy "players_join_as_self" on public.room_players for insert to authenticated with check (user_id=auth.uid());
create policy "players_update_self" on public.room_players for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "players_leave_self" on public.room_players for delete to authenticated using (user_id=auth.uid());

-- Secret rows are only readable by the matching device/user.
create policy "secrets_read_own" on public.player_secrets for select to authenticated using (user_id=auth.uid());
-- The room host may assign secret rows when the game starts; users may also create their own empty row.
create policy "secrets_host_or_self_insert" on public.player_secrets for insert to authenticated
with check (
  user_id=auth.uid()
  or exists (select 1 from public.rooms r where r.id=room_id and r.host_user_id=auth.uid())
);
create policy "secrets_host_or_self_update" on public.player_secrets for update to authenticated
using (
  user_id=auth.uid()
  or exists (select 1 from public.rooms r where r.id=room_id and r.host_user_id=auth.uid())
)
with check (
  user_id=auth.uid()
  or exists (select 1 from public.rooms r where r.id=room_id and r.host_user_id=auth.uid())
);

create policy "messages_room_members_read" on public.messages for select to authenticated
using (exists (select 1 from public.room_players p where p.room_id=messages.room_id and p.user_id=auth.uid()));
create policy "messages_room_members_write" on public.messages for insert to authenticated
with check (
  user_id=auth.uid()
  and exists (select 1 from public.room_players p where p.room_id=messages.room_id and p.user_id=auth.uid())
);

-- Supabase Realtime must include these tables.
alter publication supabase_realtime add table public.rooms;
alter publication supabase_realtime add table public.room_players;
alter publication supabase_realtime add table public.messages;
