import {
  FACTIONS, SKILLS, ROUND_PREDATION_VALUES, roleFromId, newGame, predationValue,
  setPhase, startNextRound, useHawkEye, setParasiteHost, setPackmates,
  applyHabitatCollapse, transferLife, transferPredationCard, awardSkill,
  resolvePredation, resolvePackFollowUps, livingPlayers, getAlivePlayer,
  eliminatePlayer
} from './engine.js';

const SAVE_KEY='wild-australia-evolution-clash-v2';
const $=id=>document.getElementById(id);
const esc=(value='')=>String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const asInt=value=>Number.parseInt(value,10);
let state=null,roleViewerId=null,hawkRole=null,hideLog=false;

function toast(message){const el=document.createElement('div');el.className='toast';el.textContent=message;document.body.appendChild(el);setTimeout(()=>el.remove(),2600);}
function save(){if(state)localStorage.setItem(SAVE_KEY,JSON.stringify(state));}
function normalise(){if(!state)return;state.players.forEach(p=>{p.passedStage=Boolean(p.passedStage);p.targetedStage=Boolean(p.targetedStage);p.stageUses=p.stageUses||{evasiveLeap:false,decoy:false,attackCount:0};p.skillUses=p.skillUses||{};p.decoyTargets=p.decoyTargets||[];p.packmates=p.packmates||[];});state.log=state.log||[];state.availableSkills=state.availableSkills||[];state.auctionedSkills=state.auctionedSkills||[];}
function load(){try{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return false;state=JSON.parse(raw);normalise();return true;}catch{return false;}}
function playerOptions({exclude=null,skill=null}={}){return state.players.filter(p=>p.alive&&p.id!==Number(exclude)&&(!skill||p.skills.includes(skill))).map(p=>`<option value="${p.id}">#${p.seat} ${esc(p.name)}</option>`).join('');}
function factionOptions(){return FACTIONS.map(f=>`<option value="${f.id}">${f.icon} ${esc(f.name)}</option>`).join('');}
function stageCount(){return ROUND_PREDATION_VALUES[state.round].length;}
function phaseText(){if(state.phase==='predation')return`Predation ${state.predationStage+1}/${stageCount()}`;return state.phase[0].toUpperCase()+state.phase.slice(1);}
function resetStageFlags(){state.players.forEach(p=>{p.passedStage=false;p.targetedStage=false;});}
function setDefaultFirstSeat(){const alive=livingPlayers(state);if(!alive.length){state.firstSeat=null;return;}const sceptre=alive.find(p=>p.skills.includes('bushSceptre'));if(sceptre){state.firstSeat=null;state.log.unshift(`${sceptre.name} may choose the first seat with Bushland Sceptre.`);}else{state.firstSeat=alive[Math.floor(Math.random()*alive.length)].id;state.log.unshift(`Starting seat rolled: #${state.firstSeat}.`);}}
function orderedLiving(){const alive=livingPlayers(state).sort((a,b)=>a.seat-b.seat);if(!alive.length)return[];const start=state.firstSeat&&alive.some(p=>p.id===state.firstSeat)?state.firstSeat:alive[0].id;const idx=alive.findIndex(p=>p.id===start);return [...alive.slice(idx),...alive.slice(0,idx)];}
function applyPassPenalties(){if(state.phase!=='predation')return;const amount=predationValue(state);for(const p of state.players.filter(p=>p.alive&&p.passedStage&&!p.targetedStage)){p.life-=amount;state.log.unshift(`${p.name} still refused predation and was not targeted: -${amount} life.`);if(p.life<=0)eliminatePlayer(state,p.id,null,'Refused predation');}}

function render(){if(!state){$('setupView').classList.remove('hidden');$('gameView').classList.add('hidden');$('saveBtn').classList.add('hidden');$('resetBtn').classList.add('hidden');return;}$('setupView').classList.add('hidden');$('gameView').classList.remove('hidden');$('saveBtn').classList.remove('hidden');$('resetBtn').classList.remove('hidden');$('roundText').textContent=`${state.round} / 4`;$('phaseText').textContent=phaseText();$('stakeText').textContent=state.phase==='predation'?`${predationValue(state)} life`:`${ROUND_PREDATION_VALUES[state.round].join(' / ')} life`;$('livingText').textContent=String(livingPlayers(state).length);$('roundBadge').textContent=`Round ${state.round}`;$('advanceBtn').textContent=advanceLabel();renderPlayers();renderControls();renderLog();save();}
function advanceLabel(){if(state.phase==='free')return'Start Predation';if(state.phase==='predation'&&state.predationStage+1<stageCount())return'Next Predation Stage';if(state.phase==='predation')return'Start Evolution';if(state.phase==='evolution')return state.round===4?'Finish Game':'Next Round';return'Game Finished';}
function renderPlayers(){$('playerGrid').innerHTML=state.players.map(p=>`<article class="player-card ${p.alive?'':'eliminated'}"><div class="player-head"><div><p class="player-name">${esc(p.name)}</p><span class="muted">${p.predationCards.length} predation cards</span></div><span class="seat">${p.seat}</span></div><div class="life">❤️ ${p.life}</div><div class="status-row">${!p.alive?'<span class="status-chip">ELIMINATED</span>':''}${p.protected&&p.alive?'<span class="status-chip reserve">NATURE RESERVE</span>':''}${p.torpor&&p.alive?'<span class="status-chip torpor">TORPOR</span>':''}${p.passedStage&&p.alive?'<span class="status-chip">PASS PENDING</span>':''}</div><div class="skills-mini">${p.skills.map(id=>`<span class="skill-dot" title="${esc(SKILLS[id].name)} — ${esc(SKILLS[id].description)}">${SKILLS[id].icon}</span>`).join('')||'<span class="muted">No skills yet</span>'}</div><div class="player-actions"><button data-role="${p.id}" ${p.alive?'':'disabled'}>Secret role</button></div></article>`).join('');document.querySelectorAll('[data-role]').forEach(btn=>btn.addEventListener('click',()=>openRole(asInt(btn.dataset.role))));}
function renderLog(){$('clearLogBtn').textContent=hideLog?'Show':'Hide';$('eventLog').innerHTML=hideLog?'<li>Log hidden.</li>':state.log.slice(0,80).map(x=>`<li>${esc(x)}</li>`).join('');}
function commonHawk(){const owners=state.players.filter(p=>p.alive&&p.skills.includes('hawkEye')&&!p.skillUses.hawkEye);if(!owners.length)return'';return`<div class="tool-card full"><h3>🦅 Wedge-tail Vision</h3><div class="field-grid"><div class="field"><label>Owner</label><select id="hawkOwner">${owners.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Target</label><select id="hawkTarget">${playerOptions()}</select></div></div><button id="hawkUseBtn" class="primary">Use Wedge-tail Vision</button></div>`;}
function renderControls(){if(state.phase==='free'){$('controlTitle').textContent='Free Phase';$('phaseControls').innerHTML=freeControls();}else if(state.phase==='predation'){$('controlTitle').textContent=`Predation Stage ${state.predationStage+1}`;$('phaseControls').innerHTML=predationControls();}else if(state.phase==='evolution'){$('controlTitle').textContent='Evolution Phase';$('phaseControls').innerHTML=evolutionControls();}else{$('controlTitle').textContent='Final Standings';$('phaseControls').innerHTML=finishedControls();}bindControls();}
function freeControls(){const parasite=state.players.filter(p=>p.alive&&p.skills.includes('parasite')&&!p.hostId),collapse=state.players.filter(p=>p.alive&&p.skills.includes('habitatCollapse')&&!p.skillUses.habitatCollapse),leaders=state.players.filter(p=>p.alive&&p.skills.includes('dingoPackLeader')&&!p.packmates.length);return`<div class="control-grid"><div class="tool-card"><h3>❤️ Trade life</h3><p class="muted">A player may receive at most 10 traded life per round.</p><div class="field-grid three"><div class="field"><label>From</label><select id="lifeFrom">${playerOptions()}</select></div><div class="field"><label>To</label><select id="lifeTo">${playerOptions()}</select></div><div class="field"><label>Amount</label><input id="lifeAmount" type="number" min="1" value="1"></div></div><button id="lifeTradeBtn" class="primary">Transfer life</button></div><div class="tool-card"><h3>🎴 Trade predation card</h3><div class="field-grid three"><div class="field"><label>From</label><select id="cardFrom">${playerOptions()}</select></div><div class="field"><label>To</label><select id="cardTo">${playerOptions()}</select></div><div class="field"><label>Card #</label><input id="cardNumber" type="number" min="1" max="10" value="1"></div></div><button id="cardTradeBtn" class="primary">Transfer card</button></div>${parasite.length?`<div class="tool-card"><h3>🪱 Parasite</h3><div class="field-grid"><div class="field"><label>Owner</label><select id="parasiteOwner">${parasite.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Host</label><select id="parasiteHost">${playerOptions()}</select></div></div><button id="parasiteBtn" class="primary">Lock host</button></div>`:''}${collapse.length?`<div class="tool-card"><h3>🔥 Habitat Collapse</h3><div class="field-grid"><div class="field"><label>Owner</label><select id="collapseOwner">${collapse.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Habitat</label><select id="collapseFaction">${factionOptions()}</select></div></div><button id="collapseBtn" class="primary">Trigger collapse</button></div>`:''}${leaders.length?`<div class="tool-card full"><h3>🐺 Dingo Pack Leader</h3><div class="field-grid three"><div class="field"><label>Leader</label><select id="packLeader">${leaders.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><div class="field"><label>Packmate 1</label><select id="packOne">${playerOptions()}</select></div><div class="field"><label>Packmate 2</label><select id="packTwo">${playerOptions()}</select></div></div><button id="packBtn" class="primary">Lock pack</button></div>`:''}${commonHawk()}</div>`;}
function predationControls(){const decoys=playerOptions({skill:'decoy'}),sceptre=livingPlayers(state).some(p=>p.skills.includes('bushSceptre')),order=orderedLiving();return`<div class="control-grid"><div class="tool-card full"><h3>🎯 Predation</h3><div class="field-grid"><div class="field"><label>Predator</label><select id="predator">${playerOptions()}</select></div><div class="field"><label>Original prey</label><select id="prey">${playerOptions()}</select></div></div><div class="field-grid"><div class="field"><label>Decoy (optional)</label><select id="decoy"><option value="">None</option>${decoys}</select></div><div class="field"><label>Tail Drop cards</label><input id="tailDropCards" placeholder="e.g. 2,7"></div></div><label class="check-row"><input id="evasive" type="checkbox"> Prey uses Evasive Leap</label><button id="predationBtn" class="primary">Resolve Predation · ${predationValue(state)} life</button></div><div class="tool-card"><h3>⏭ Pass for now</h3><p class="muted">A passer can still attack later in this stage. If still passed at stage end and never targeted, they lose ${predationValue(state)} life.</p><div class="field"><label>Player</label><select id="passPlayer">${playerOptions()}</select></div><button id="passBtn" class="primary">Mark Pass</button></div><div class="tool-card"><h3>🧭 First seat</h3><p class="muted">${sceptre?'Bushland Sceptre may choose.':'Otherwise use a random roll.'}</p><div class="field-grid"><div class="field"><label>First player</label><select id="firstSeat">${playerOptions()}</select></div><div class="field"><label>Set / roll</label><button id="firstSeatBtn" class="ghost">${sceptre?'Set selected':'Roll random'}</button></div></div><div class="order-strip">${order.map(p=>`<span>${p.seat}. ${esc(p.name)}</span>`).join('')}</div></div><div class="tool-card"><h3>🌱 Nature Reserve</h3><p class="muted">Rounds 1–2: a predation loser cannot be targeted again that round. Rounds 3–4 remove the reserve.</p></div>${commonHawk()}</div>`;}
function evolutionControls(){return`<div class="skill-market">${state.availableSkills.map(id=>{const s=SKILLS[id];return`<div class="skill-card"><div class="icon">${s.icon}</div><h3>${esc(s.name)}</h3><p>${esc(s.description)}</p><div class="field"><label>Winner</label><select id="winner-${id}">${playerOptions()}</select></div><div class="field"><label>Bid</label><input id="bid-${id}" type="number" min="1" value="1"></div><button class="primary auction-btn" data-skill="${id}">Award skill</button></div>`;}).join('')||'<div class="tool-card"><h3>All skills auctioned</h3><p class="muted">Advance to continue.</p></div>'}</div>${commonHawk()}`;}
function finishedControls(){const winners=new Set(state.winnerIds||[]);return`<div class="control-grid">${[...state.players].sort((a,b)=>b.life-a.life).map(p=>`<div class="tool-card"><h3>${winners.has(p.id)?'🏆 ':''}${esc(p.name)}</h3><p><strong>${p.life} life</strong> · ${esc(roleFromId(p.roleId).label)}</p><p class="muted">${p.skills.map(id=>SKILLS[id].name).join(', ')||'No skills'}</p></div>`).join('')}</div>`;}
function bindControls(){const on=(id,fn)=>{const el=$(id);if(el)el.addEventListener('click',fn);};on('lifeTradeBtn',()=>safe(()=>transferLife(state,asInt($('lifeFrom').value),asInt($('lifeTo').value),asInt($('lifeAmount').value)),'Life transferred.'));on('cardTradeBtn',()=>safe(()=>transferPredationCard(state,asInt($('cardFrom').value),asInt($('cardTo').value),asInt($('cardNumber').value)),'Card transferred.'));on('parasiteBtn',()=>safe(()=>setParasiteHost(state,asInt($('parasiteOwner').value),asInt($('parasiteHost').value)),'Parasite host locked.'));on('collapseBtn',()=>safe(()=>applyHabitatCollapse(state,asInt($('collapseOwner').value),$('collapseFaction').value),'Habitat Collapse resolved.'));on('packBtn',()=>safe(()=>setPackmates(state,asInt($('packLeader').value),[asInt($('packOne').value),asInt($('packTwo').value)]),'Packmates locked.'));on('hawkUseBtn',useHawk);on('passBtn',()=>safe(()=>{const p=getAlivePlayer(state,asInt($('passPlayer').value));p.passedStage=true;state.log.unshift(`${p.name} passed for now.`);},'Pass marked.'));on('firstSeatBtn',()=>safe(()=>{const sceptre=livingPlayers(state).some(p=>p.skills.includes('bushSceptre'));if(sceptre)state.firstSeat=asInt($('firstSeat').value);else{const alive=livingPlayers(state);state.firstSeat=alive[Math.floor(Math.random()*alive.length)].id;$('firstSeat').value=String(state.firstSeat);}state.log.unshift(`Predation starts from seat ${state.firstSeat}.`);},'Starting seat set.'));on('predationBtn',doPredation);document.querySelectorAll('.auction-btn').forEach(btn=>btn.addEventListener('click',()=>{const id=btn.dataset.skill;safe(()=>awardSkill(state,id,asInt($(`winner-${id}`).value),asInt($(`bid-${id}`).value)),`${SKILLS[id].name} awarded.`);}));}
function doPredation(){try{const attackerId=asInt($('predator').value),action={attackerId,defenderId:asInt($('prey').value),decoyId:$('decoy').value?asInt($('decoy').value):null,useEvasiveLeap:$('evasive').checked};const tail=$('tailDropCards').value.trim();if(tail)action.tailDropCards=tail.split(',').map(x=>asInt(x.trim())).filter(Number.isFinite);const result=resolvePredation(state,action),attacker=state.players.find(p=>p.id===attackerId),actual=state.players.find(p=>p.id===result.redirectedDefenderId);if(attacker)attacker.passedStage=false;if(actual)actual.targetedStage=true;let pack=[];if(attacker?.alive&&attacker.skills.includes('dingoPackLeader')&&attacker.packmates.length===2&&actual?.alive)pack=resolvePackFollowUps(state,attackerId,actual.id);save();render();const winner=state.players.find(p=>p.id===result.winnerId),loser=state.players.find(p=>p.id===result.loserId);showMessage('PREDATION RESULT',`${winner?.name||'Winner'} wins`,`<div class="result-card"><strong>${esc(winner?.name||'Winner')}</strong> wins ${result.amount} life against <strong>${esc(loser?.name||'Loser')}</strong>.</div>${result.tailDropUsed?'<p>🦎 Tail Drop prevented prey life loss.</p>':''}${pack.length?`<p>🐺 ${pack.length} Pack follow-up attacks resolved.</p>`:''}`);}catch(err){toast(err.message);}}
function useHawk(){try{const owner=asInt($('hawkOwner').value),target=asInt($('hawkTarget').value);if(owner===target)throw new Error('Choose another player.');hawkRole=useHawkEye(state,owner,target);$('hawkTargetName').textContent=state.players.find(p=>p.id===target).name;$('hawkRevealGate').classList.remove('hidden');$('hawkReveal').classList.add('hidden');save();render();$('hawkDialog').showModal();}catch(err){toast(err.message);}}
function advance(){try{if(state.phase==='free'){setPhase(state,'predation',0);resetStageFlags();setDefaultFirstSeat();}else if(state.phase==='predation'){applyPassPenalties();if(state.predationStage+1<stageCount()){setPhase(state,'predation',state.predationStage+1);resetStageFlags();setDefaultFirstSeat();}else setPhase(state,'evolution');}else if(state.phase==='evolution')startNextRound(state);render();}catch(err){toast(err.message);}}
function openRole(id){roleViewerId=id;const p=state.players.find(p=>p.id===id);$('roleOwner').textContent=p.name;$('roleRevealGate').classList.remove('hidden');$('roleReveal').classList.add('hidden');$('roleDialog').showModal();}
function revealRole(){const p=state.players.find(p=>p.id===roleViewerId),r=roleFromId(p.roleId);$('roleIcon').textContent=r.icon;$('roleName').textContent=r.label;$('roleRule').textContent=r.id==='joker'?'As predator: always wins. As prey: always loses.':'Rank cycle: K › Q › J › K. Same rank uses the habitat cycle.';$('roleRevealGate').classList.add('hidden');$('roleReveal').classList.remove('hidden');}
function revealHawk(){if(!hawkRole)return;$('hawkRoleIcon').textContent=hawkRole.icon;$('hawkRoleName').textContent=hawkRole.label;$('hawkRevealGate').classList.add('hidden');$('hawkReveal').classList.remove('hidden');}
function rules(){return`<div class="rules-grid"><section class="rules-block"><h3>Core setup</h3><p>Exactly 10 players, 20 starting life, hidden identities and predation cards numbered 1–10.</p></section><section class="rules-block"><h3>Match-ups</h3><p><strong>K › Q › J › K.</strong> Same rank: <strong>Outback › Reef › Bushland › Outback</strong>. Platypus Joker wins as predator and loses as prey.</p></section><section class="rules-block"><h3>Four rounds</h3><p>Predation values: 2; 3; 4 then 5; 6 then 7. Rounds 1–2 use Nature Reserve.</p></section><section class="rules-block"><h3>Pass rule</h3><p>A player may skip initially, then still choose to prey later. If they still refuse by stage end and were not targeted, they lose that stage's predation value.</p></section></div><h3 style="margin:22px 0 10px">Australian skill deck</h3><div class="skills-rules">${Object.values(SKILLS).map(s=>`<div class="skill-rule"><span class="icon">${s.icon}</span><div><strong>${esc(s.name)}</strong><br><span class="muted">Round ${s.round} · ${esc(s.description)}</span></div></div>`).join('')}</div>`;}
function safe(fn,msg){try{fn();save();render();toast(msg);}catch(err){toast(err.message);}}
function showMessage(kicker,title,body){$('messageKicker').textContent=kicker;$('messageTitle').textContent=title;$('messageBody').innerHTML=body;$('messageDialog').showModal();}
function exportSave(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`wild-australia-round-${state.round}.json`;a.click();URL.revokeObjectURL(url);}
function reset(){if(!confirm('Start a new game? Current local save will be deleted.'))return;localStorage.removeItem(SAVE_KEY);state=null;location.reload();}

for(let i=1;i<=10;i++)$('nameGrid').insertAdjacentHTML('beforeend',`<label class="name-field"><span>SEAT ${i}</span><input name="player${i}" value="Player ${i}" maxlength="24" required></label>`);
$('setupForm').addEventListener('submit',e=>{e.preventDefault();const names=Array.from(new FormData(e.currentTarget).values()).map(v=>String(v).trim());if(new Set(names.map(n=>n.toLowerCase())).size!==10)return toast('Please use 10 different player names.');try{state=newGame(names);normalise();save();render();}catch(err){toast(err.message);}});
$('advanceBtn').addEventListener('click',advance);$('rulesBtn').addEventListener('click',()=>{$('rulesContent').innerHTML=rules();$('rulesDialog').showModal();});$('saveBtn').addEventListener('click',exportSave);$('resetBtn').addEventListener('click',reset);$('clearLogBtn').addEventListener('click',()=>{hideLog=!hideLog;renderLog();});$('revealRoleBtn').addEventListener('click',revealRole);$('hawkRevealBtn').addEventListener('click',revealHawk);document.querySelectorAll('[data-close]').forEach(btn=>btn.addEventListener('click',()=>$(btn.dataset.close).close()));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close();}));
if(load())render();else render();
